// Code generated by MockGen. DO NOT EDIT.
// Source: internal/kafka/producer_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProducerInterface is a mock of ProducerInterface interface.
type MockProducerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProducerInterfaceMockRecorder
}

// MockProducerInterfaceMockRecorder is the mock recorder for MockProducerInterface.
type MockProducerInterfaceMockRecorder struct {
	mock *MockProducerInterface
}

// NewMockProducerInterface creates a new mock instance.
func NewMockProducerInterface(ctrl *gomock.Controller) *MockProducerInterface {
	mock := &MockProducerInterface{ctrl: ctrl}
	mock.recorder = &MockProducerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerInterface) EXPECT() *MockProducerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerInterface)(nil).Close))
}

// SendCartItemAdded mocks base method.
func (m *MockProducerInterface) SendCartItemAdded(cartId, sku string, count int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCartItemAdded", cartId, sku, count, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCartItemAdded indicates an expected call of SendCartItemAdded.
func (mr *MockProducerInterfaceMockRecorder) SendCartItemAdded(cartId, sku, count, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCartItemAdded", reflect.TypeOf((*MockProducerInterface)(nil).SendCartItemAdded), cartId, sku, count, status)
}

// SendCartItemFailed mocks base method.
func (m *MockProducerInterface) SendCartItemFailed(cartId, sku string, count int, status, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCartItemFailed", cartId, sku, count, status, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCartItemFailed indicates an expected call of SendCartItemFailed.
func (mr *MockProducerInterfaceMockRecorder) SendCartItemFailed(cartId, sku, count, status, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCartItemFailed", reflect.TypeOf((*MockProducerInterface)(nil).SendCartItemFailed), cartId, sku, count, status, reason)
}
