// Code generated by MockGen. DO NOT EDIT.
// Source: internal/stockclient/stock_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "cart/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// GetBySKU mocks base method.
func (m *MockStockRepository) GetBySKU(ctx context.Context, sku uint32) (models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", ctx, sku)
	ret0, _ := ret[0].(models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockStockRepositoryMockRecorder) GetBySKU(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockStockRepository)(nil).GetBySKU), ctx, sku)
}
