// Code generated by MockGen. DO NOT EDIT.
// Source: internal/kafka/producer_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProducerInterface is a mock of ProducerInterface interface.
type MockProducerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProducerInterfaceMockRecorder
}

// MockProducerInterfaceMockRecorder is the mock recorder for MockProducerInterface.
type MockProducerInterfaceMockRecorder struct {
	mock *MockProducerInterface
}

// NewMockProducerInterface creates a new mock instance.
func NewMockProducerInterface(ctrl *gomock.Controller) *MockProducerInterface {
	mock := &MockProducerInterface{ctrl: ctrl}
	mock.recorder = &MockProducerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerInterface) EXPECT() *MockProducerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerInterface)(nil).Close))
}

// SendSKUCreated mocks base method.
func (m *MockProducerInterface) SendSKUCreated(sku string, price float64, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSKUCreated", sku, price, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSKUCreated indicates an expected call of SendSKUCreated.
func (mr *MockProducerInterfaceMockRecorder) SendSKUCreated(sku, price, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSKUCreated", reflect.TypeOf((*MockProducerInterface)(nil).SendSKUCreated), sku, price, count)
}

// SendStockChanged mocks base method.
func (m *MockProducerInterface) SendStockChanged(sku string, count int, price float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendStockChanged", sku, count, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendStockChanged indicates an expected call of SendStockChanged.
func (mr *MockProducerInterfaceMockRecorder) SendStockChanged(sku, count, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStockChanged", reflect.TypeOf((*MockProducerInterface)(nil).SendStockChanged), sku, count, price)
}
