// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "stocks/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockStockUseCase is a mock of StockUseCase interface.
type MockStockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStockUseCaseMockRecorder
}

// MockStockUseCaseMockRecorder is the mock recorder for MockStockUseCase.
type MockStockUseCaseMockRecorder struct {
	mock *MockStockUseCase
}

// NewMockStockUseCase creates a new mock instance.
func NewMockStockUseCase(ctrl *gomock.Controller) *MockStockUseCase {
	mock := &MockStockUseCase{ctrl: ctrl}
	mock.recorder = &MockStockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockUseCase) EXPECT() *MockStockUseCaseMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStockUseCase) Add(ctx context.Context, item models.StockItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStockUseCaseMockRecorder) Add(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStockUseCase)(nil).Add), ctx, item)
}

// Delete mocks base method.
func (m *MockStockUseCase) Delete(ctx context.Context, sku uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sku)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStockUseCaseMockRecorder) Delete(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStockUseCase)(nil).Delete), ctx, sku)
}

// GetBySKU mocks base method.
func (m *MockStockUseCase) GetBySKU(ctx context.Context, sku uint32) (models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", ctx, sku)
	ret0, _ := ret[0].(models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockStockUseCaseMockRecorder) GetBySKU(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockStockUseCase)(nil).GetBySKU), ctx, sku)
}

// ListByLocation mocks base method.
func (m *MockStockUseCase) ListByLocation(ctx context.Context, location string, pageSize, currentPage int64) ([]models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLocation", ctx, location, pageSize, currentPage)
	ret0, _ := ret[0].([]models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLocation indicates an expected call of ListByLocation.
func (mr *MockStockUseCaseMockRecorder) ListByLocation(ctx, location, pageSize, currentPage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLocation", reflect.TypeOf((*MockStockUseCase)(nil).ListByLocation), ctx, location, pageSize, currentPage)
}
