// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "stocks/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStockRepository) Delete(ctx context.Context, sku uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sku)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStockRepositoryMockRecorder) Delete(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStockRepository)(nil).Delete), ctx, sku)
}

// GetBySKU mocks base method.
func (m *MockStockRepository) GetBySKU(ctx context.Context, sku uint32) (models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", ctx, sku)
	ret0, _ := ret[0].(models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockStockRepositoryMockRecorder) GetBySKU(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockStockRepository)(nil).GetBySKU), ctx, sku)
}

// GetByUserSKU mocks base method.
func (m *MockStockRepository) GetByUserSKU(ctx context.Context, userID int64, sku uint32) (models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserSKU", ctx, userID, sku)
	ret0, _ := ret[0].(models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserSKU indicates an expected call of GetByUserSKU.
func (mr *MockStockRepositoryMockRecorder) GetByUserSKU(ctx, userID, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserSKU", reflect.TypeOf((*MockStockRepository)(nil).GetByUserSKU), ctx, userID, sku)
}

// GetSKUInfo mocks base method.
func (m *MockStockRepository) GetSKUInfo(ctx context.Context, sku uint32) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSKUInfo", ctx, sku)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSKUInfo indicates an expected call of GetSKUInfo.
func (mr *MockStockRepositoryMockRecorder) GetSKUInfo(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSKUInfo", reflect.TypeOf((*MockStockRepository)(nil).GetSKUInfo), ctx, sku)
}

// InsertStockItem mocks base method.
func (m *MockStockRepository) InsertStockItem(ctx context.Context, item models.StockItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStockItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStockItem indicates an expected call of InsertStockItem.
func (mr *MockStockRepositoryMockRecorder) InsertStockItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStockItem", reflect.TypeOf((*MockStockRepository)(nil).InsertStockItem), ctx, item)
}

// ListByLocation mocks base method.
func (m *MockStockRepository) ListByLocation(ctx context.Context, location string, pageSize, currentPage int64) ([]models.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLocation", ctx, location, pageSize, currentPage)
	ret0, _ := ret[0].([]models.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLocation indicates an expected call of ListByLocation.
func (mr *MockStockRepositoryMockRecorder) ListByLocation(ctx, location, pageSize, currentPage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLocation", reflect.TypeOf((*MockStockRepository)(nil).ListByLocation), ctx, location, pageSize, currentPage)
}

// UpdateCount mocks base method.
func (m *MockStockRepository) UpdateCount(ctx context.Context, userID int64, sku uint32, newCount uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCount", ctx, userID, sku, newCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCount indicates an expected call of UpdateCount.
func (mr *MockStockRepositoryMockRecorder) UpdateCount(ctx, userID, sku, newCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCount", reflect.TypeOf((*MockStockRepository)(nil).UpdateCount), ctx, userID, sku, newCount)
}
